version: '3.8'

services:
  stridex:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/subjects"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s